name: 'Deploy to GCP - DEV'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      REGION: us-central1
      LB_IP_CIDR_RANGE: '10.128.0.0/24'
      PROXY_ONLY_IP_CIDR_RANGE: '10.128.2.0/23'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_DEV_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_DEV_SA_EMAIL }}
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy
        run: terraform init && terraform apply -var="project_id=${{ secrets.GCP_DEV_PROJECT_ID }}" -var="region=$REGION" -var="artifact_registry_location=$REGION" -var="lb_ip_cidr_range=$LB_IP_CIDR_RANGE" -var="proxy_only_ip_cidr_range=$PROXY_ONLY_IP_CIDR_RANGE" -var="users_service_image=${{ secrets.GCP_DEV_USERS_SERVICE_IMAGE }}" -var="profiles_service_image=${{ secrets.GCP_DEV_PROFILES_SERVICE_IMAGE }}" --auto-approve
        working-directory: ./deploy/gcp/terraform/environments/dev
