name: 'Deploy to GCP - DEV'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      REGION: us-central1
      FIRESTORE_LOCATION_ID: us-central
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_DEV_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_DEV_SA_EMAIL }}
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy
        run: terraform init && terraform apply -var="project_id=${{ secrets.GCP_DEV_PROJECT_ID }}" -var="region=$REGION" -var="firestore_location_id=$FIRESTORE_LOCATION_ID" -var="artifact_registry_location=$REGION" -var="users_service_image=${{ secrets.GCP_DEV_USERS_SERVICE_IMAGE }}" --auto-approve
        working-directory: ./deploy/gcp/terraform/environments/dev
